application: osclubofcas
version: 1
runtime: python
api_version: 1

default_expiration: "7d 5h"


inbound_services:
- channel_presence


handlers:
- url: /static
  static_dir: static

- url: /chat/?.*
  script: chat.py

- url: /_ah/channel/connected/
  script: chat.py

- url: /_ah/channel/disconnected/
  script: chat.py

- url: /_ah/admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin


#error_handlers:
#  - file: static/404.html

#  - error_code: over_quota
#    file: static/over_quota.html 